name: Deploy React Vite to aaPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Only deploy when Muthumari-1993 pushes
    if: github.actor == 'Muthumari-1993'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          VITE_STRAPI_URL: https://qubistrapiadmin.unitdtechnologies.com
        run: npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to aaPanel
        run: |
          rsync -avz --delete \
            --exclude='.user.ini' \
            --exclude='.htaccess' \
            --exclude='.well-known' \
            dist/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}/